export const pubRouter = [
    {
        // 퍼블리싱 - 퍼블 화면 리스트path: "/pub/page",title: "_PublishingList",depth1: "PublishingList",depth2: "",depth3: "",status: "",
    },
    {
        path: "/pub/page/guidelogin",
        title: "_Guide_Login",
        depth1: "Guide",
        depth2: "Login",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidebutton",
        title: "_Guide_Button",
        depth1: "Guide",
        depth2: "Button",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidecheck",
        title: "_Guide_Check",
        depth1: "Guide",
        depth2: "Check",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidedate",
        title: "_Guide_Date/Time",
        depth1: "Guide",
        depth2: "Date",
        depth3: "Time",
        status: "완료",
    },
    {
        path: "/pub/page/guideeditor",
        title: "_Guide_Editor",
        depth1: "Guide",
        depth2: "Editor",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guideflag",
        title: "_Guide_Flag",
        depth1: "Guide",
        depth2: "Flag",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guideform",
        title: "_Guide_Form",
        depth1: "Guide",
        depth2: "Form",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidegrid",
        title: "_Guide_Grid/Paging",
        depth1: "Guide",
        depth2: "Grid",
        depth3: "Paging",
        status: "완료",
    },
    {
        path: "/pub/page/guideinput",
        title: "_Guide_Input",
        depth1: "Guide",
        depth2: "Input",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guideloading",
        title: "_Guide_Loading",
        depth1: "Guide",
        depth2: "Loading",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidemodal",
        title: "_Guide_Modal/Alert",
        depth1: "Guide",
        depth2: "Modal",
        depth3: "Alert",
        status: "완료",
    },
    {
        path: "/pub/page/guidesearch",
        title: "_Guide_Search",
        depth1: "Guide",
        depth2: "Search",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidetab",
        title: "_Guide_Tab",
        depth1: "Guide",
        depth2: "Tab",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidetext",
        title: "_Guide_Text",
        depth1: "Guide",
        depth2: "Text",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidetooltip",
        title: "_Guide_Tooltip",
        depth1: "Guide",
        depth2: "Tooltip",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/guidetopbar",
        title: "_Guide_Topbar",
        depth1: "Guide",
        depth2: "Topbar",
        depth3: "",
        status: "완료",
    },
    // Error
    {
        path: "/pub/page/error",
        title: "_에러페이지_404",
        depth1: "에러페이지",
        depth2: "404",
        depth3: "",
        status: "완료",
    },
    // PO
    {
        path: "/pub/page/PO050001",
        title: "_PO_수입정산관리",
        depth1: "PO",
        depth2: "수입정산관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO010001",
        title: "_BO_Home",
        depth1: "BO",
        depth2: "Home",
        depth3: "",
        status: "완료",
    },
    // 00 로그인
    {
        path: "/pub/page/BO000001",
        title: "_로그인",
        depth1: "로그인",
        depth2: "",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO000002",
        title: "_로그인>2차인증_Loading",
        depth1: "로그인",
        depth2: "2차인증",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO000003",
        title: "_로그인>인증번호입력",
        depth1: "로그인",
        depth2: "인증번호입력",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO000004",
        title: "_로그인>계정등록신청>계정구분",
        depth1: "로그인",
        depth2: "계정등록신청",
        depth3: "계정구분",
        status: "완료",
    },
    {
        path: "/pub/page/BO000006",
        title: "_로그인>계정등록신청_(ID BO000006_/_BO000009)",
        depth1: "로그인",
        depth2: "계정등록신청",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO000007",
        title: "_로그인>계정등록신청>신청완료",
        depth1: "로그인",
        depth2: "계정등록신청",
        depth3: "신청완료",
        status: "완료",
    },
    {
        path: "/pub/page/BO000011",
        title: "_로그인>아이디/비밀번호찾기_(ID BO000011_/_BO000013)",
        depth1: "로그인",
        depth2: "아이디/비밀번호찾기",
        depth3: "",
        status: "완료",
    },
    // 02 사용자관리
    {
        path: "/pub/page/BO021001",
        title: "_사용자관리>회원관리_목록_(search-box Collapse)_Loading",
        depth1: "사용자관리",
        depth2: "회원관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO021002",
        title: "_사용자관리>회원관리",
        depth1: "사용자관리",
        depth2: "회원관리",
        depth3: "",
        status: "완료",
    },
    // {
    //     path: "/pub/page/drawer02",
    //     title: "_사용자관리_Drawer_&_Modal",
    //     depth1: "사용자관리",
    //     depth2: "Drawer & Modal",
    //     depth3: "",
    //     status: "",
    // },
    // 03 파트너/시설관리
    {
        path: "/pub/page/BO031001",
        title: "_파트너/시설관리>파트너관리",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO031002",
        title: "_파트너/시설관리>파트너관리>계약등록",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "계약등록",
        status: "완료",
    },
    {
        path: "/pub/page/BO031003",
        title: "_파트너/시설관리>파트너관리>계약상세>계약조회",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "계약상세/계약조회",
        status: "완료",
    },
    {
        path: "/pub/page/BO031015",
        title: "_파트너/시설관리>파트너관리>계약상세>파트너계정관리",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "계약상세/파트너계정관리",
        status: "완료",
    },
    {
        path: "/pub/page/BO031016",
        title: "_파트너/시설관리>파트너관리>계약상세>주차장등록관리>목록",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "계약상세/주차장등록관리/목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO031017",
        title: "_파트너/시설관리>파트너관리>계약상세>배정자관리>목록",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "계약상세/배정자관리/목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO031023",
        title: "_파트너/시설관리>파트너관리>계약상세>주차장등록관리>조회",
        depth1: "파트너/시설관리",
        depth2: "파트너관리",
        depth3: "계약상세/주차장등록관리/조회",
        status: "완료",
    },
    {
        path: "/pub/page/BO033001",
        title: "_파트너/시설관리>배정자관리",
        depth1: "파트너/시설관리",
        depth2: "배정자공유현황관리",
        depth3: "배정자공유현황관리 목록",
        status: "완료",
    },

    {
        path: "/pub/page/BO034001",
        title: "_파트너/시설관리>시설관리",
        depth1: "파트너/시설관리",
        depth2: "시설관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/drawer03",
        title: "_파트너/시설관리_Drawer_&_Modal",
        depth1: "파트너/시설관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
    // 04 전시컨텐츠관리
    {
        path: "/pub/page/BO041001",
        title: "_전시컨텐츠관리>공지관리>목록",
        depth1: "전시/컨텐츠관리",
        depth2: "공지관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO042001",
        title: "_전시컨텐츠관리>이벤트관리>목록",
        depth1: "전시/컨텐츠관리",
        depth2: "이벤트관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO042004",
        title: "_전시컨텐츠관리>이벤트관리>이벤트등록",
        depth1: "전시/컨텐츠관리",
        depth2: "이벤트관리",
        depth3: "이벤트등록",
        status: "완료",
    },
    {
        path: "/pub/page/BO045001",
        title: "_전시컨텐츠관리>약관관리>목록",
        depth1: "전시/컨텐츠관리",
        depth2: "약관관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO046001",
        title: "_전시컨텐츠관리>배너/팝업관리>목록",
        depth1: "전시/컨텐츠관리",
        depth2: "배너/팝업관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO047001",
        title: "_전시컨텐츠관리>FAQ관리>목록",
        depth1: "전시/컨텐츠관리",
        depth2: "FAQ관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO048001",
        title: "_전시컨텐츠관리>이용안내관리>목록",
        depth1: "전시/컨텐츠관리",
        depth2: "이용안내관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/drawer04",
        title: "_전시컨텐츠관리_Drawer_&_Modal",
        depth1: "전시/컨텐츠관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
    // 05 쿠폰포인트관리
    {
        path: "/pub/page/BO051001",
        title: "_쿠폰포인트관리>쿠폰관리",
        depth1: "쿠폰/포인트관리",
        depth2: "쿠폰관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO051002",
        title: "_쿠폰포인트관리>쿠폰관리>등록",
        depth1: "쿠폰/포인트관리",
        depth2: "쿠폰관리",
        depth3: "등록",
        status: "완료",
    },
    {
        path: "/pub/page/BO052001",
        title: "_쿠폰포인트관리>포인트관리",
        depth1: "쿠폰/포인트관리",
        depth2: "포인트관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO053001",
        title: "_쿠폰포인트관리>포인트상품권관리",
        depth1: "쿠폰/포인트관리",
        depth2: "포인트상품권관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/drawer05",
        title: "_쿠폰포인트관리_Drawer_&_Modal",
        depth1: "쿠폰/포인트관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
    // 06 문의관리
    {
        path: "/pub/page/BO061001",
        title: "_문의관리>공유신청관리>목록",
        depth1: "문의관리",
        depth2: "공유신청관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO061002",
        title: "_문의관리>공유신청관리>조회/상세",
        depth1: "문의관리",
        depth2: "공유신청관리",
        depth3: "조회/상세",
        status: "완료",
    },
    {
        path: "/pub/page/BO062001",
        title: "_문의관리>1:1문의관리>목록",
        depth1: "문의관리",
        depth2: "1:1문의관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO062002",
        title: "_문의관리>1:1문의관리>조회/상세",
        depth1: "문의관리",
        depth2: "1:1문의관리",
        depth3: "조회/상세",
        status: "완료",
    },
    {
        path: "/pub/page/BO064001",
        title: "_문의관리>부정주차신고관리>목록",
        depth1: "문의관리",
        depth2: "부정주차신고관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO064002",
        title: "_문의관리>부정주차신고관리>조회/상세",
        depth1: "문의관리",
        depth2: "부정주차신고관리",
        depth3: "조회/상세",
        status: "완료",
    },
    {
        path: "/pub/page/BO064001a",
        title: "_문의관리>제보관리>목록",
        depth1: "문의관리",
        depth2: "제보관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO064002a",
        title: "_문의관리>제보관리>조회/상세",
        depth1: "문의관리",
        depth2: "제보관리",
        depth3: "조회/상세",
        status: "완료",
    },
    {
        path: "/pub/page/BO065001",
        title: "_문의관리>결제대행관리",
        depth1: "문의관리",
        depth2: "결제대행관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/drawer06",
        title: "_문의관리_Drawer_&_Modal",
        depth1: "문의관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
    // 07 이력관리
    {
        path: "/pub/page/BO091001",
        title: "_이력관리>접속이력관리>목록",
        depth1: "이력관리",
        depth2: "접속이력관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO092001",
        title: "_이력관리>다운로드이력관리>목록",
        depth1: "이력관리",
        depth2: "다운로드이력관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO093001",
        title: "_이력관리>약관이력관리>목록",
        depth1: "이력관리",
        depth2: "약관이력관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO094001",
        title: "_이력관리>정보변경이력관리>목록",
        depth1: "이력관리",
        depth2: "주차권 요금변경 이력 관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/drawer09",
        title: "_이력관리_Drawer_&_Modal",
        depth1: "이력관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
    // 08 정산관리
    {
        path: "/pub/page/BO071001",
        title: "_정산관리>결제관리>목록",
        depth1: "정산관리",
        depth2: "결제관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO071004",
        title: "_정산관리>주차장 결제관리>목록",
        depth1: "정산관리",
        depth2: "주차장 결제관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/BO072001",
        title: "_정산관리>정산관리>목록",
        depth1: "정산관리",
        depth2: "정산관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/drawer07",
        title: "_정산관리_Drawer_&_Modal",
        depth1: "정산관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
    // 09 관리자설정관리
    {
        path: "/pub/page/BO081001",
        title: "_관리자설정관리>계정신청관리>목록",
        depth1: "관리자 설정 관리",
        depth2: "계정 신청 관리",
        depth3: "목록",
        status: "완료",
    },
    // {
    //     path: "/pub/page/BO082001",
    //     title: "_관리자설정관리>메뉴권한관리>목록",
    //     depth1: "관리자 설정 관리",
    //     depth2: "메뉴권한관리",
    //     depth3: "목록",
    //     status: "",
    // },
    // {
    //     path: "/pub/page/BO082001a",
    //     title: "_관리자설정관리>메뉴권한관리>목록",
    //     depth1: "관리자 설정 관리",
    //     depth2: "메뉴권한관리",
    //     depth3: "목록",
    // status: "",},
    {
        path: "/pub/page/BO083001",
        title: "_관리자설정관리>공통코드관리",
        depth1: "관리자 설정 관리",
        depth2: "공통 코드 관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO084001",
        title: "_관리자설정관리>APP버전관리",
        depth1: "관리자 설정 관리",
        depth2: "APP버전관리",
        depth3: "",
        status: "완료",
    },

    {
        path: "/pub/page/BO087001",
        title: "_관리자설정관리>유의사항관리",
        depth1: "관리자 설정 관리",
        depth2: "유의사항관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO085001",
        title: "_관리자설정관리>운영컨텐츠관리",
        depth1: "관리자 설정 관리",
        depth2: "운영컨텐츠 관리",
        depth3: "",
        status: "완료",
    },
    {
        path: "/pub/page/BO088001",
        title: "_관리자설정관리>관리자계정관리>목록",
        depth1: "관리자 설정 관리",
        depth2: "관리자 계정 관리",
        depth3: "목록",
        status: "완료",
    },
    {
        path: "/pub/page/drawer08",
        title: "_관리자설정관리_Drawer_&_Modal",
        depth1: "관리자 설정 관리",
        depth2: "Drawer & Modal",
        depth3: "",
        status: "완료",
    },
];
